const ALPHABET = [
  { letter: "A", word: "Apple", emoji: "🍎", telugu: "ఆపిల్", hint: "A is for Apple — a red fruit" },
  { letter: "B", word: "Ball", emoji: "⚽", telugu: "బంతి", hint: "B is for Ball — we play with it" },
  { letter: "C", word: "Cat", emoji: "🐱", telugu: "పిల్లి", hint: "C is for Cat — says meow!" },
  { letter: "D", word: "Dog", emoji: "🐶", telugu: "కుక్క", hint: "D is for Dog — a loyal friend" },
  { letter: "E", word: "Elephant", emoji: "🐘", telugu: "ఏనుగు", hint: "E is for Elephant — big and strong" },
  { letter: "F", word: "Fish", emoji: "🐟", telugu: "చేప", hint: "F is for Fish — swims in water" },
  { letter: "G", word: "Grapes", emoji: "🍇", telugu: "ద్రాక్ష", hint: "G is for Grapes — small and sweet" },
  { letter: "H", word: "House", emoji: "🏠", telugu: "ఇల్లు", hint: "H is for House — where we live" },
  { letter: "I", word: "Ice Cream", emoji: "🍦", telugu: "ఐస్ క్రీమ్", hint: "I is for Ice Cream — cold and yummy" },
  { letter: "J", word: "Juice", emoji: "🧃", telugu: "జ్యూస్", hint: "J is for Juice — drink it up!" },
  { letter: "K", word: "Kite", emoji: "🪁", telugu: "గాలిపటం", hint: "K is for Kite — flies in the sky" },
  { letter: "L", word: "Lion", emoji: "🦁", telugu: "సింహం", hint: "L is for Lion — king of jungle" },
  { letter: "M", word: "Moon", emoji: "🌙", telugu: "చంద్రుడు", hint: "M is for Moon — shines at night" },
  { letter: "N", word: "Nest", emoji: "🪺", telugu: "గూడు", hint: "N is for Nest — birds live here" },
  { letter: "O", word: "Orange", emoji: "🍊", telugu: "నారింజ", hint: "O is for Orange — round fruit" },
  { letter: "P", word: "Parrot", emoji: "🦜", telugu: "చిలుక", hint: "P is for Parrot — colorful bird" },
  { letter: "Q", word: "Queen", emoji: "👸", telugu: "రాణి", hint: "Q is for Queen — wears a crown" },
  { letter: "R", word: "Rainbow", emoji: "🌈", telugu: "ఇంద్రధనుస్సు", hint: "R is for Rainbow — many colors" },
  { letter: "S", word: "Sun", emoji: "☀️", telugu: "సూర్యుడు", hint: "S is for Sun — gives us light" },
  { letter: "T", word: "Tree", emoji: "🌳", telugu: "చెట్టు", hint: "T is for Tree — tall and green" },
  { letter: "U", word: "Umbrella", emoji: "☂️", telugu: "గొడుగు", hint: "U is for Umbrella — stops rain" },
  { letter: "V", word: "Violin", emoji: "🎻", telugu: "వయోలిన్", hint: "V is for Violin — makes music" },
  { letter: "W", word: "Water", emoji: "💧", telugu: "నీరు", hint: "W is for Water — we need it daily" },
  { letter: "X", word: "Xylophone", emoji: "🎵", telugu: "జైలోఫోన్", hint: "X is for Xylophone — musical instrument" },
  { letter: "Y", word: "Yak", emoji: "🐂", telugu: "యాక్", hint: "Y is for Yak — mountain animal" },
  { letter: "Z", word: "Zebra", emoji: "🦓", telugu: "జీబ్రా", hint: "Z is for Zebra — black and white stripes" },
];
